### ISSUE TITLE
Body property not available in calendar items retrieved through find_item(calendar_view)

### ISSUE THREAD

**Issue by kmorrissey-mersive** [otris/ews-cpp#48]
I'm trying to use the library for accessing calendar items. There was no example file for this case, so I wrote one, which can be seen at https://gist.github.com/kmorrissey-mersive/750bfb98e87e1a6adce977c7e1ddc088. The example lists all calendar items for 3/1/2017-3/31/2017.

The example mostly works, but the CalendarItem's Body and Resources come back as empty, even though I do have a meeting with a body and an assigned room.

I built the test program using Windows and Visual Studio 2012. I don't know how to tell what version of Exchange I'm accessing, although I expect it is fairly current.

Is this a problem with the library, or am I misusing it and not retrieving the body nd resources correctly?

**Comment by kmorrissey-mersive** [comment]
I have expanded the test cases at https://gist.github.com/kmorrissey-mersive/6f9d598b135bbd3b32b9f7f91b3ccb33 to demonstrate calendar_item.get_body() not returning expected results on a calendar item found through find_item(calendar_view, folder).

**Comment by bkircher** [comment]
Hi Karen! Thanks for reporting and the example code and additional test case. With that I was able  to reproduce the problem and understand your issue quickly.

> Is this a problem with the library, or am I misusing it and not retrieving the body and resources correctly?

Well, kind of both 😉

EWS's [`<FindItem/>` operation](https://msdn.microsoft.com/en-us/library/office/aa566107(v=exchg.150).aspx) takes a `<BaseShape/>` as parameter that determines how much information is included in a `<FindItemResponse/>`. This parameter can be one of `IdOnly`, `Default`, or `AllProperties`.

The problem with the library is that the overload set of `find_item` is not clear on what `<BaseShape>` it uses when it renders the SOAP request.  It even does not allow the user to request additional properties, like an item's `<Body/>` for instance.

The second problem is with EWS itself. Actually it is not really a problem but rather an inconvenience. When you do a `<FindItem/>`operation using a [`<CalendarView/>`](https://msdn.microsoft.com/en-us/library/office/aa564515(v=exchg.150).aspx) you are limited in the properties you get back from the server. ⊗

As I read the documentation there is no reliable way in getting the body property in the operation back from the server. So one solution would be to do a `find_item` call with the wanted `calendar_view` and `base_shape::id_only` as parameters first and then--in a subsequent call--retrieving the wanted calendar item including it's body with a `get_item` call on those item_ids.

I will try to alter the API so that the user can set the `<BaseShape>` in a `find_item(calendar_view)` call (#49) and come up with an example that covers your use case (#50).

⊗ At least it seems so. When I do include a `<t:AdditionalProperties><t:FieldURI FieldURI="item:Body" /></t:AdditionalProperties>` in the request together with a `<CalendarView/>`, I get an error response back saying "Property is not valid for this operation".

**Comment by kmorrissey-mersive** [comment]
Benjamin,

Thank you for the reply. I wrote you another message this morning before I saw this reply to my issue.

I already figured out that I could do a get_calendar_item() using the ID from find_item().

I didn’t quite understand something. Is the use of base_shape::id_only something I cn somehow pass to find_item(), or are you saying you intend to provide a way?

**Comment by bkircher** [comment]
> I already figured out that I could do a get_calendar_item() using the ID from find_item().

Exactly this would be the correct solution. `<CalendarView>` is kind of special.

> I didn’t quite understand something. Is the use of base_shape::id_only something I cn somehow pass to find_item(), or are you saying you intend to provide a way?

Currently there is no way for you to pass `base_shape::id_only ` to `find_item()` but this is wrong and will be fixed in the future.

**Comment by bkircher** [comment]
Hi Karen!

We added a new example in `find_calendar_items.cpp` that should cover finding calendar items with a CalendarView and then retrieving all properties of each individual calendar item in one subsequent SOAP call. The code is in current master and will be part of the next release.
