### ISSUE TITLE
Certificate verification failed

### ISSUE THREAD

**Issue by SebastianBecker2** [otris/ews-cpp#86]
I tried the example from the README.md using cURL 7.46.0 DLL from `Confused by Code` as you recommended.

But `service.create_item(message, ews::message_disposition::send_and_save_copy);` throws a curl exception `Peer certificate cannot be authenticated with given CA certificates`.

From my limited understanding, the self-signed X509 certificate gets rejected by libcurl because it can't be verified using the CA store. So, ews-cpp would need to deactivate libcurls certificate verification with `curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, FALSE);`.

The certificate is properly installed. Using the EwsEditor, I have no problems using the EWS.

I'm no expert on TLS or cURL, so I'm not really sure if I'm on the right track or totally misguided.
Maybe you can point me to the right direction.

**Comment by bkircher** [comment]
Hi there. You might want to pass 

```
-DDISABLE_TLS_CERT_VERIFICATION=ON
```

when invoking cmake or manually define

```c++
#define EWS_DISABLE_TLS_CERT_VERIFICATION
```

before including the ews.hpp header file. This will skip TLS certificate peer checks against any cert store (essentially the same as passing `--insecure` or `-k` to curl binary, I believe). Enabling this will issue a compiler warning, too.

This will keep you going for now (for further run the examples) but I think this is not what you actually want to happen in production because it is inherently insecure.

Currently, ews-cpp uses libcurl's default bundle of CA certificates, which is usually the system's default.


So we have two options left: 

1. add your self-signed certificate's CA to the system defaul'ts CA chain or
2. configure ews-cpp to use a custom path to look up CAs

The latter does not work in ews-cpp, currently. If you need this to work, we should open an issue for this. (And PRs always welcome, of course :smile: ) AFAIK, we could specify alternate certificates with the CURLOPT_CAINFO option or the CURLOPT_CAPATH option.

**Comment by bkircher** [comment]
BTW, 7.46.0 is quite old. (This is however totally unrelated to your issue, of course.) You can easily build libcurl yourself on Windows from source with https://github.com/bkircher/curl-winbuild and I even think Windows 10 comes now with curl bundled since a recent update.

**Comment by SebastianBecker2** [comment]
Big thanks for the immediate help!

I really need to dig deeper into TLS certificates for this project.
EWS_DISABLE_TLS_CERT_VERIFICATION works for now to proof that ews-cpp is the right way to go.

I got the newest version of libcurl to work now. Thanks!
